@echo off
echo Installing dependencies...
npm install --legacy-peer-deps
echo Pushing schema...
npx prisma db push
echo Generating client...
npx prisma generate
echo Seeding admin...
npx tsx prisma/seed-admin.ts
echo Done!
